# BSPWM Nord Rice Config

[theme]
name        = "ricelinux-bspwm-nord"                         # Name shown to the user on login
id          = "com.github.zaedus.ricelinux-bspwm-nord"       # Name the rice is installed under (ex: '/opt/ricelinux/com.github.zaedus.ricelinux-bspwm-nord')
description = "A *very* simple BSPWM configuration"          # Description of the theme
version     = "1.0.0"                                        # Version of the theme

[window-manager]
name           = "bspwm"                            # Name of the window manager
executable     = "/usr/bin/bspwm"                   # Executable to start the window manager
params         = "-c {0}/bspwmrc"                    # Command line paremters (Note: all paths are relative to the theme's install location)
display-server = "xorg"                             # Can be either 'xorg' or 'wayland' 

[packages]
pacman = [
    "bspwm",                # Must include window manager as dependent
    "sxhkd",                # Hotkey daemon
    "bash",                 # Not necessary, but recommended to include all dependencies regardless of if they are installed by default
    "rofi",                 # Launcher
    "alacritty",            # Terminal
]

aur = [
    "ttf-envy-code-r",      # Font for alacritty and rofi prompt
]

[git]
repo = "https://github.com/Zaedus/ricelinux-bspwm-nord.git"   # The git repository
commit = "f0ccf8247d4e75cd0732f41d705e22570b3bdd1f"           # The specific commit of the finished theme
